apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:
  containers:
  - image: nitisha2/stress
    imagePullPolicy: Always
    name: stress
    command: ["sleep", "200"]
    resources:
     requests:
       cpu: "150m"
       memory: "200Mi"
     limts:
       cpu: "200m"
       memory: "300Mi"
