apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default: 
     cpu: 500m
    defaultRequest: 
    cpu: 500m
    max:
      cpu: "1"
    min:
     cpu: 100m # 1 CPU = 1000m
    type: Container 
---
apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:
  containers:
  - image: nitisha2/stress
    imagePullPolicy: Always
    name: stress
    command: ["sleep", "200"]