apiVersion: v1
kind: Pod
metadata:
 name: labels
 labels:
  course: docker
  duration: 25hrs
  trainer: shiva
 annotations:
  org.kuberentes.docker.nitisha: nitisha
spec:
 containers:
 - name: nginx
   image: nginx