apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      env:
      - name: course
        value: docker
      - name: trainer
        value: shiva