apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: 
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::478811340053:user/EKS-CLUSTER
      username: EKS-CLUSTER  
kind: ConfigMap
metadata:
  creationTimestamp: "2023-04-05T14:29:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "8381"
  uid: 04fc6c1d-39e1-480a-815c-992ec55879e3
